"""eigtth Migration

Revision ID: 56365b404b54
Revises: e3548e6a04d6
Create Date: 2019-02-28 12:19:17.459204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56365b404b54'
down_revision = 'e3548e6a04d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey')
    )
    # ### end Alembic commands ###
