"""nineth Migration

Revision ID: 7e7cf69b5fb7
Revises: 56365b404b54
Create Date: 2019-03-01 14:41:40.035322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7cf69b5fb7'
down_revision = '56365b404b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitch_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_category', sa.String(length=255), nullable=True),
    sa.Column('category_description', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('username', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('votes', sa.Integer(), nullable=True))
    op.drop_column('comments', 'vote')
    op.drop_column('comments', 'name')
    op.add_column('pitchs', sa.Column('category_id', sa.String(length=255), nullable=True))
    op.add_column('pitchs', sa.Column('pitch_id', sa.String(length=255), nullable=True))
    op.drop_column('pitchs', 'name')
    op.drop_column('pitchs', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitchs', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pitchs', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitchs', 'pitch_id')
    op.drop_column('pitchs', 'category_id')
    op.add_column('comments', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('vote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'votes')
    op.drop_column('comments', 'username')
    op.drop_column('comments', 'comment')
    op.drop_table('vote')
    op.drop_table('pitch_categories')
    # ### end Alembic commands ###
