"""sixth Migration

Revision ID: e3548e6a04d6
Revises: fbdde6efe57c
Create Date: 2019-02-28 11:44:12.444141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3548e6a04d6'
down_revision = 'fbdde6efe57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('vote', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'vote')
    # ### end Alembic commands ###
